import type { ResolvedWasmModule, ResolvedGrammars } from "../types.js";

/**
 * Generate the virtual runtime module source code.
 *
 * This produces JavaScript that:
 * 1. Imports the host and each grammar's JS glue module from resolved paths
 * 2. Uses `new URL(literal, import.meta.url)` for each WASM file so the
 *    bundler emits them as hashed static assets
 * 3. Calls `__initRuntime(...)` from the runtime-core with resolved references
 * 4. Re-exports the public API
 */
export function generateRuntimeModule(
  host: ResolvedWasmModule,
  resolved: ResolvedGrammars,
): string {
  const grammars = [...resolved.grammars.entries()];

  const grammarImports = grammars
    .map(([lang, g]) => {
      const v = toIdentifier(lang);
      return [
        `import * as ${v}Module from ${JSON.stringify(g.js)};`,
        `const ${v}Wasm = new URL(${JSON.stringify(g.wasm)}, import.meta.url);`,
      ].join("\n");
    })
    .join("\n");

  const grammarEntries = grammars
    .map(([lang]) => {
      const v = toIdentifier(lang);
      return `    ${JSON.stringify(lang)}: { module: ${v}Module, wasmUrl: ${v}Wasm },`;
    })
    .join("\n");

  return `\
// Auto-generated by unplugin-arborium
import * as hostModule from ${JSON.stringify(host.js)};
import { __initRuntime, highlight, loadGrammar, getAvailableLanguages, isLanguageAvailable } from "unplugin-arborium/runtime-core";

${grammarImports}

const hostWasm = new URL(${JSON.stringify(host.wasm)}, import.meta.url);

__initRuntime({
  host: {
    module: hostModule,
    wasmUrl: hostWasm,
  },
  grammars: {
${grammarEntries}
  },
});

export { highlight, loadGrammar, getAvailableLanguages, isLanguageAvailable };
`;
}

/** Convert a language name like "c-sharp" to a valid JS identifier like "cSharp" */
function toIdentifier(lang: string): string {
  return lang
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
