import type { ResolvedWasmModule, ResolvedGrammars } from "../types.js";

/**
 * Generate the virtual runtime module source code.
 *
 * This produces JavaScript that:
 * 1. Imports the host and each grammar's JS glue module from resolved paths
 * 2. Uses `new URL(literal, import.meta.url)` for each WASM file so the
 *    bundler emits them as hashed static assets
 * 3. Calls `setConfig(...)` from @arborium/arborium with resolve hooks that
 *    redirect loading to the bundled modules instead of CDN
 * 4. Re-exports the public API
 */
export function generateRuntimeModule(
  host: ResolvedWasmModule,
  resolved: ResolvedGrammars,
  arboriumPath: string,
): string {
  const grammars = [...resolved.grammars.entries()];
  const languages = grammars.map(([lang]) => lang);

  const grammarImports = grammars
    .map(([lang, g]) => {
      const v = toIdentifier(lang);
      return [
        `import * as ${v}Module from ${JSON.stringify(g.js)};`,
        `const ${v}Wasm = new URL(${JSON.stringify(g.wasm)}, import.meta.url);`,
      ].join("\n");
    })
    .join("\n");

  const grammarEntries = grammars
    .map(([lang]) => {
      const v = toIdentifier(lang);
      return `  ${JSON.stringify(lang)}: { module: ${v}Module, wasm: ${v}Wasm },`;
    })
    .join("\n");

  return `\
// Auto-generated by unplugin-arborium
import * as hostModule from ${JSON.stringify(host.js)};
import { setConfig, highlight, loadGrammar, detectLanguage, extractLanguageFromClass, normalizeLanguage, availableLanguages, pluginVersion } from ${JSON.stringify(arboriumPath)};
${grammarImports}

const __hostWasm = new URL(${JSON.stringify(host.wasm)}, import.meta.url);
const __grammars = {
${grammarEntries}
};

setConfig({
  resolveHostJs: () => hostModule,
  resolveHostWasm: () => fetch(__hostWasm),
  resolveJs: ({ language }) => __grammars[language]?.module,
  resolveWasm: ({ language }) => { const u = __grammars[language]?.wasm; return u ? fetch(u) : undefined; },
});

const __bundled = ${JSON.stringify(languages)};
export function getAvailableLanguages() { return [...__bundled]; }
export function isLanguageAvailable(language) { return __bundled.includes(language); }
export { highlight, loadGrammar, detectLanguage, extractLanguageFromClass, normalizeLanguage, availableLanguages, pluginVersion };
`;
}

/** Convert a language name like "c-sharp" to a valid JS identifier like "cSharp" */
function toIdentifier(lang: string): string {
  return lang
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}
